const ADD_PRODUCT_TO_CATALOGUE = 'ADD_PRODUCT_TO_CATALOGUE';
const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
const ADD_PRODUCT_TO_FAVOURITES = 'ADD_PRODUCT_TO_FAVOURITES';

export {
  ADD_PRODUCT_TO_CATALOGUE,
  ADD_PRODUCT_TO_CART,
  ADD_PRODUCT_TO_FAVOURITES,
};
