const ADD_PRODUCT_TO_CATALOGUE = 'ADD_PRODUCT_TO_CATALOGUE';
const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
const ADD_PRODUCT_TO_FAVOURITES = 'ADD_PRODUCT_TO_FAVOURITES';
const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
const DELETE_PRODUCT_FROM_FAVOURITES = 'DELETE_PRODUCT_FROM_FAVOURITES';
const DELETE_ALL_PRODUCTS = 'DELETE_ALL_PRODUCTS';

export {
  ADD_PRODUCT_TO_CATALOGUE,
  ADD_PRODUCT_TO_CART,
  ADD_PRODUCT_TO_FAVOURITES,
  DELETE_PRODUCT_FROM_CART,
  DELETE_PRODUCT_FROM_FAVOURITES,
  DELETE_ALL_PRODUCTS,
};
